In [167]:
import numpy as np
import scipy.linalg
import time

In [151]:
def const_diag_offset(N, value, offset):

    # Initialize A
    A = np.zeros((N,N), dtype=np.float64)

    # Assign the (offset) diagonal element with const value
    for i in range(N):
        column = i + offset
        if column>=0 and column<N:
            A[i][column] = value
    
    return A

In [152]:
# The dimmension
n = 100

# Generate the matrix in exercise 6
A =   const_diag_offset(n,  1, -2) \
    + const_diag_offset(n, -4, -1) \
    + const_diag_offset(n,  6,  0) \
    + const_diag_offset(n, -4,  1) \
    + const_diag_offset(n,  1,  2) 

delta = np.zeros((n,n), dtype=np.float64)
delta[0][0]  = 3
delta[98][98]=-1
delta[98][99]= 2
delta[99][98]= 2
delta[99][99]=-5

A = A + delta

# Generate b vector
b = np.full(n, 1.)

In [153]:
# Check A matrix
A

array([[ 9., -4.,  1., ...,  0.,  0.,  0.],
       [-4.,  6., -4., ...,  0.,  0.,  0.],
       [ 1., -4.,  6., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  6., -4.,  1.],
       [ 0.,  0.,  0., ..., -4.,  5., -2.],
       [ 0.,  0.,  0., ...,  1., -2.,  1.]])

Exercise 6-1

In [168]:
start_time = time.time()

# Using scipy for LU decomposition
lu, piv = scipy.linalg.lu_factor(A)

# Solve Ax = b
x = scipy.linalg.lu_solve((lu, piv), b)

print("--- %s seconds ---" % (time.time() - start_time))

--- 0.0017728805541992188 seconds ---


In [165]:
np.set_printoptions(2)
print(x)

[1.26e+03 7.48e+03 1.85e+04 3.44e+04 5.48e+04 7.99e+04 1.09e+05 1.43e+05
 1.81e+05 2.24e+05 2.70e+05 3.21e+05 3.75e+05 4.33e+05 4.95e+05 5.61e+05
 6.30e+05 7.02e+05 7.78e+05 8.58e+05 9.40e+05 1.03e+06 1.11e+06 1.21e+06
 1.30e+06 1.40e+06 1.50e+06 1.60e+06 1.71e+06 1.82e+06 1.93e+06 2.04e+06
 2.16e+06 2.27e+06 2.39e+06 2.52e+06 2.64e+06 2.77e+06 2.89e+06 3.02e+06
 3.16e+06 3.29e+06 3.43e+06 3.56e+06 3.70e+06 3.84e+06 3.98e+06 4.13e+06
 4.27e+06 4.42e+06 4.56e+06 4.71e+06 4.86e+06 5.01e+06 5.16e+06 5.32e+06
 5.47e+06 5.63e+06 5.78e+06 5.94e+06 6.09e+06 6.25e+06 6.41e+06 6.57e+06
 6.73e+06 6.89e+06 7.05e+06 7.21e+06 7.38e+06 7.54e+06 7.70e+06 7.87e+06
 8.03e+06 8.20e+06 8.36e+06 8.53e+06 8.69e+06 8.86e+06 9.02e+06 9.19e+06
 9.36e+06 9.52e+06 9.69e+06 9.86e+06 1.00e+07 1.02e+07 1.04e+07 1.05e+07
 1.07e+07 1.09e+07 1.10e+07 1.12e+07 1.14e+07 1.15e+07 1.17e+07 1.19e+07
 1.20e+07 1.22e+07 1.24e+07 1.25e+07]


In [156]:
# Check if the solution x is correct
np.allclose(A @ x - b, np.zeros((n,)))

True

Exercise 6-2

In [157]:
def a2ab(N, a, l, u):

    # Initialize ab
    ab = np.zeros((l+u+1,N))

    # Transform a to ab
    for i in range(N):
        for j in range(max(i-l, 0), min(u+i+1, N)):
            # print((i,j), '=>', (u + i - j, j))
            ab[u + i - j, j] = a[i,j]
                
    return ab

In [169]:
start_time = time.time()

# For matrix A, there is two nonzero diagonal below the main diagonal (l = 2), 
# and two above (u = 2). The diagonal banded form of the matrix is:
AB = a2ab(N=n, a=A, l=2, u=2)

# Solve for x
x_band = scipy.linalg.solve_banded((2, 2), AB, b)

print("--- %s seconds ---" % (time.time() - start_time))

--- 0.0007059574127197266 seconds ---


In [166]:
np.set_printoptions(2)
print(x_band)

[1.26e+03 7.47e+03 1.85e+04 3.44e+04 5.48e+04 7.99e+04 1.09e+05 1.43e+05
 1.81e+05 2.24e+05 2.70e+05 3.21e+05 3.75e+05 4.33e+05 4.95e+05 5.61e+05
 6.30e+05 7.02e+05 7.78e+05 8.58e+05 9.40e+05 1.03e+06 1.11e+06 1.21e+06
 1.30e+06 1.40e+06 1.50e+06 1.60e+06 1.71e+06 1.82e+06 1.93e+06 2.04e+06
 2.16e+06 2.27e+06 2.39e+06 2.52e+06 2.64e+06 2.77e+06 2.89e+06 3.02e+06
 3.16e+06 3.29e+06 3.43e+06 3.56e+06 3.70e+06 3.84e+06 3.98e+06 4.13e+06
 4.27e+06 4.42e+06 4.56e+06 4.71e+06 4.86e+06 5.01e+06 5.16e+06 5.32e+06
 5.47e+06 5.63e+06 5.78e+06 5.94e+06 6.09e+06 6.25e+06 6.41e+06 6.57e+06
 6.73e+06 6.89e+06 7.05e+06 7.21e+06 7.38e+06 7.54e+06 7.70e+06 7.87e+06
 8.03e+06 8.20e+06 8.36e+06 8.53e+06 8.69e+06 8.86e+06 9.02e+06 9.19e+06
 9.36e+06 9.52e+06 9.69e+06 9.86e+06 1.00e+07 1.02e+07 1.04e+07 1.05e+07
 1.07e+07 1.09e+07 1.10e+07 1.12e+07 1.14e+07 1.15e+07 1.17e+07 1.19e+07
 1.20e+07 1.22e+07 1.24e+07 1.25e+07]


In [161]:
# Verify the solution
np.allclose(A @ x_band - b, np.zeros((n,)))

True

Exercise 6-3

In [208]:
def matrix_norm1(A, n):
    absolute_column_sum = [np.abs(A[:][j]).sum() for j in range(n)]
    return np.array(absolute_column_sum).max()


In [209]:
# The L1 norm of matrix A
A_norm1 = matrix_norm1(A, n)
A_norm1

16.0

In [204]:
# The L1 norm if matrix A^-1
A_inv_norm1 = matrix_norm1(np.linalg.inv(A), n)
A_inv_norm1

12541675.002266005

In [210]:
# The condition number
cond_A = A_norm1*A_inv_norm1
cond_A

200666800.03625607

Example of scipy.linalg.lu_factor from website

In [43]:
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
lu, piv = scipy.linalg.lu_factor(A)

piv_py = [2, 0, 3, 1]
L, U = np.tril(lu, k=-1) + np.eye(4), np.triu(lu)

In [48]:
# Check if the LU decomposition was correct
A[piv_py] - L @ U

array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 8.8817842e-16,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 8.8817842e-16, -4.4408921e-16,  4.4408921e-16,  0.0000000e+00]])

Example of scipy.linalg.solve_banded from website

In [129]:
# There is one nonzero diagonal below the main diagonal (l = 1), and two above (u = 2)
a = np.array([[5,  2, -1,  0,  0],    
              [1,  4,  2, -1,  0],    
              [0,  1,  3,  2, -1],   
              [0,  0,  1,  2,  2], 
              [0,  0,  0,  1,  1]])   


The matrix a is stored in ab using the matrix diagonal ordered form


ab[u + i - j, j] == a[i,j]

In [62]:
# ab represent a*b
ab = np.array([[0,  0, -1, -1, -1],
               [0,  2,  2,  2,  2],
               [5,  4,  3,  2,  1],
               [1,  1,  1,  1,  0]])

b = np.array([0, 1, 2, 2, 3])

# Solve ax = b
x = scipy.linalg.solve_banded((1, 2), ab, b)
x

array([-2.37288136,  3.93220339, -4.        ,  4.3559322 , -1.3559322 ])

In [143]:
# Check ab
ab - a2ab(N=5, a=a, l=1, u=2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])